HOSTS:
  centos-70-x64:
    roles:
      - test
    platform: el-7-x86_64
    box : skyovp/centos7-puppet4
    box_url : https://s3-eu-west-1.amazonaws.com/sky-vagrant-boxes/centos7-puppet4.template.box
    hypervisor : vagrant
    volumes:
      test:
        size: 10000
CONFIG:
  type: aio
  vagrant_memsize: 4096
